name: Run Gradle on PRs
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Containers
        run: docker-compose up -d
      - name: Execute Gradle build
        run: ./gradlew build
